# Generated by Django 5.2.3 on 2025-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_answers_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('total_questions', models.IntegerField(verbose_name='Общее количество вопросов')),
                ('correct_answers', models.IntegerField(verbose_name='Правильных ответов')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
            ],
            options={
                'verbose_name': 'Результат викторины',
                'verbose_name_plural': 'Результаты викторины',
            },
        ),
    ]
